version: "3.8"
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-pipeline-api}"
    image: localstack/localstack:3.8
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      DEBUG: ${DEBUG:-0}
      AWS_DEFAULT_REGION: eu-west-2
      SERVICES: sqs, s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack/volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/bootstrap:/etc/localstack/init/ready.d/"
    networks:
      ls:
        # Set the container IP address in the 10.0.2.0/24 subnet
        ipv4_address: 10.0.2.20

  pipeline-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_COMMIT: placeholder
    environment:
      COLLECTION_BUCKET: local-collection-data
      AWS_DEFAULT_REGION: eu-west-2
      AWS_ENDPOINT_URL: http://localstack:4566
      DUCKDB_S3_ENDPOINT: s3.localhost.localstack.cloud:4566
      DUCKDB_S3_USE_SSL: "false"
      AWS_REGION: eu-west-2
      LOGGING_LEVEL: DEBUG
      USE_AWS_CREDENTIAL_CHAIN: "false"

#      AWS_ACCESS_KEY_ID: "***"
#      AWS_SECRET_ACCESS_KEY: "***"
#      AWS_SESSION_TOKEN: "***"
#      AWS_CREDENTIAL_EXPIRATION: 2024-11-12T10:51:26Z
    restart: on-failure
    ports:
      - "8000:8000"
    dns:
      # Set the DNS server to be the LocalStack container
      - 10.0.2.20
    networks:
      - ls
  # test:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     TEST_ENV: "true"
  #     AWS_ACCESS_KEY_ID: testing
  #     AWS_SECRET_ACCESS_KEY: testing
  #     AWS_DEFAULT_REGION: us-west-2
  #     AWS_ENDPOINT_URL: http://localstack:4566
  #     COLLECTION_BUCKET: test-bucket
  #     LOGGING_LEVEL: DEBUG
  #     USE_AWS_CREDENTIAL_CHAIN: "false"
  #   command: ["pytest", "tests/"]
  #   depends_on:
  #     - localstack
  #   networks:
  #     - ls
networks:
  # localstack network is used so that requests to localstack resolve from containers
  # See https://docs.localstack.cloud/references/network-troubleshooting/endpoint-url/
  ls:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24